db_engine="postgres"

[http]
https=false
port=4200

[security]
auth_token="qwertyuiopasdfghjklmnbvcxzqwert1"
aes_key="qwertyuiopasdfghjklmnbvcxzqwerty"

[upload]
chunk_upload_dir="./data/chunk"
full_file_dir="./data/fullfile"
max_chunk_size=5000000
max_file_size_upload=20000000
max_transform_file_size=50000000

[postgresql]
host = "localhost"
port = 5432
user = "mahi"
database = "mahi"
password = ""
max_conns = 50